name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build tests
      run: gcc -Iinclude -Iunity tests/test_led_control.c src/led_control.c unity/unity.c -o test.out

    - name: Run unit tests
      run: ./test.out